repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: tox
        name: "[evolutionary-snake] Run linters"
        entry: bash -c 'poetry run tox -e linters'
        language: system
        pass_filenames: false
