# Ruff configuration is based of the default configuration:
# https://docs.astral.sh/ruff/configuration/

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Allow imports relative to the "src" and "test" directories.
src = ["src", "tests"]

# Same as Black
line-length = 88
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
select = [
    "ALL", # https://docs.astral.sh/ruff/rules/
]
ignore = [
    "TD002", # Missing author in to-do
    "FIX002", # Line contains to-do, consider resolving the issue
    "CPY001", # Missing copyright notice at top of file
    # COM812: https://docs.astral.sh/ruff/rules/missing-trailing-comma/#formatter-compatibility
    "COM812", # Ruff format is incompatible with this rule, and makes it redundant.
    # ISC001: https://github.com/astral-sh/ruff/issues/8272
    "ISC001", # Same as above.
]
fixable = ["ALL"]
unfixable = [
    "D", # Dont fix docstyle from others
]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = [
    "S101", # asserts allowed in tests...
]

# Use google styleguide convention
[lint.pydocstyle]
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
